/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fire_Department;

import Medical_Department.AlertsClass;
import Medical_Department.AlertsDirectory;
import UI.AddFireVehicle;
import UI.Login;
import UI.RegisterFireAdmin;
import User.PersonClass;
import static aed_project.AED_Project.fireAdmin;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author jagru
 */

public class FireAdminMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form FireAdminMainFrame
     */
    public FireAdminMainFrame() {
        initComponents();
    }
    
    public void getFireAdmin(PersonClass fire) {
        fireAdmin = fire;
    }
    
    private static int check=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Vehicles List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alerts");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        jButton4.setText("Edit Profile");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Vehicle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Login login = new Login();
        login.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"ID", "Name", "Address","Zip","Reason","Status"};
        int count=0;
        for(int i=0;i<AlertsDirectory.getInstance().getAlertsDir().size();i++) {
            if(AlertsDirectory.getInstance().getAlertsDir().get(i).getDept().equals("Fire")) {
                count++;
            }
        }
        check=1;
        String[][] rows = new String[count][6];
        int j=0;
        for(int i=0;i<AlertsDirectory.getInstance().getAlertsDir().size();i++) {
            if(AlertsDirectory.getInstance().getAlertsDir().get(i).getDept().equals("Fire")) {
                int zip = AlertsDirectory.getInstance().getAlertsDir().get(i).getZip();
                int id = AlertsDirectory.getInstance().getAlertsDir().get(i).getStateID();
                rows[j][0] = Integer.toString(id);
                rows[j][1] = AlertsDirectory.getInstance().getAlertsDir().get(i).getName();
                rows[j][2] = AlertsDirectory.getInstance().getAlertsDir().get(i).getAddress();
                rows[j][3] = Integer.toString(zip);
                rows[j][4] = AlertsDirectory.getInstance().getAlertsDir().get(i).getDesc();
                rows[j][5] = AlertsDirectory.getInstance().getAlertsDir().get(i).getStatus();
                j++;
            }
        }
        DefaultTableModel model = new DefaultTableModel (rows, columnNames);
        table.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        check=0;
        this.hide();
        RegisterFireAdmin fa = new RegisterFireAdmin();
        fa.getRole("Fire Admin");
        AdminsDirectory.getInstance().viewFireAdmin(fireAdmin,fa);
        fa.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] columnNames = {"Vehicle Type", "Vehicle Number", "Status"};
        check=2;
        String[][] rows = new String[FireVehicleDirectory.getInstance().getFireVehicleDir().size()][3];
        int j=0;
        for(int i=0;i<FireVehicleDirectory.getInstance().getFireVehicleDir().size();i++) {
            int number = FireVehicleDirectory.getInstance().getFireVehicleDir().get(i).getVehicleNumber();
            rows[j][0] = FireVehicleDirectory.getInstance().getFireVehicleDir().get(i).getVehicleType();
            rows[j][1] = Integer.toString(number);
            rows[j][2] = FireVehicleDirectory.getInstance().getFireVehicleDir().get(i).getStatus();
            j++;
        }
        DefaultTableModel model = new DefaultTableModel (rows, columnNames);
        table.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.hide();
        AddFireVehicle fv = new AddFireVehicle();
        fv.show();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        JComboBox cb = null;
        int index = table.getSelectedRow();
        TableModel model = table.getModel();
        int input;
        if(check!=0) {
            if(check==2) {
                String status[] = {"Available","Unavailable"};
                cb = new JComboBox(status);
                input = JOptionPane.showConfirmDialog(this, cb, "Update Status", JOptionPane.DEFAULT_OPTION);
                try{
                    String type = model.getValueAt(index, 0).toString();
                    String no = model.getValueAt(index, 1).toString();
                    int id = Integer.parseInt(no);
                    FireVehicleClass amb = new FireVehicleClass(type, id, (String)cb.getSelectedItem());
                    for(int i=0;i<FireVehicleDirectory.getInstance().getFireVehicleDir().size();i++) {
                        if(FireVehicleDirectory.getInstance().getFireVehicleDir().get(i).getVehicleNumber()==id) {
                            FireVehicleDirectory.getInstance().updateVehicle(amb, i);
                            break;
                        }
                    }
                    model.setValueAt((String)cb.getSelectedItem(), index, 2);
                } catch(Exception e) {
                    System.out.println(e);
                }
            }
            else{
                String status[] = {"Fire Vehicle is on it's way","Emergency is taken care of"};
                cb = new JComboBox(status);
                input = JOptionPane.showConfirmDialog(this, cb, "Update Status", JOptionPane.DEFAULT_OPTION);
                try{
                    String desc = model.getValueAt(index, 4).toString();
                    String name = model.getValueAt(index, 1).toString();
                    String address = model.getValueAt(index, 2).toString();
                    String zip = model.getValueAt(index, 3).toString();
                    int zip_code = Integer.parseInt(zip);
                    String stateID = model.getValueAt(index, 0).toString();
                    int id = Integer.parseInt(stateID);
                    AlertsClass alert = new AlertsClass(id, name, address, zip_code, "Fire", desc, (String)cb.getSelectedItem());
                    for(int i=0;i<AlertsDirectory.getInstance().getAlertsDir().size();i++) {
                        if(AlertsDirectory.getInstance().getAlertsDir().get(i).getStateID()==id 
                                && AlertsDirectory.getInstance().getAlertsDir().get(i).getDept().equals("Fire") 
                                && AlertsDirectory.getInstance().getAlertsDir().get(i).getDesc().equals(desc)) {
                            AlertsDirectory.getInstance().updateAlert(alert, i);
                            break;
                        }
                    }
                    model.setValueAt((String)cb.getSelectedItem(), index, 5);
                } catch(Exception e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FireAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FireAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FireAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FireAdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FireAdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
